CREATE TABLE usuario (
    id_usuario SERIAL PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    role TEXT DEFAULT 'user'
);

CREATE TABLE secoes (
    id_secao SERIAL PRIMARY KEY,
    nome_secao TEXT NOT NULL,
    ordem INT GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE modulos (
    id_modulo SERIAL PRIMARY KEY,
    id_secao INT NOT NULL,
    nome_modulo TEXT NOT NULL,
    ordem INT GENERATED BY DEFAULT AS IDENTITY,
    FOREIGN KEY (id_secao) REFERENCES secoes(id_secao)
);

CREATE TABLE submodulos (
    id_submodulo SERIAL PRIMARY KEY,
    id_modulo INT NOT NULL,
    nome_submodulo TEXT NOT NULL,
    ordem INT,
    FOREIGN KEY (id_modulo) REFERENCES modulos(id_modulo)
);

CREATE TABLE texto (
    id_texto SERIAL PRIMARY KEY,
    titulo TEXT,
    corpo TEXT,
    referencias TEXT
);

CREATE TABLE aula (
    id_aula SERIAL PRIMARY KEY,
    id_submodulo INT NOT NULL,
    id_texto INT,
    url_video TEXT,
    id_quiz INT,
    url_imagem TEXT,
    FOREIGN KEY (id_submodulo) REFERENCES submodulos(id_submodulo),
    FOREIGN KEY (id_texto) REFERENCES texto(id_texto)
);

CREATE TABLE progresso_usuario (
    id_progresso SERIAL PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_aula INT NOT NULL,
    porcentagem NUMERIC,
    concluido BOOLEAN DEFAULT FALSE,
    ultima_interacao TIMESTAMP,
    data_conclusao TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
    FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

CREATE TABLE perguntas (
    id_pergunta SERIAL PRIMARY KEY,
    id_dificuldade INT,
    enunciado TEXT NOT NULL,
    id_aula INT,
    FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

CREATE TABLE alternativas (
    id_alternativa SERIAL PRIMARY KEY,
    id_pergunta INT NOT NULL,
    enunciado TEXT NOT NULL,
    correta BOOLEAN,
    explicacao TEXT,
    FOREIGN KEY (id_pergunta) REFERENCES perguntas(id_pergunta)
);

CREATE TABLE quiz_aula (
    id_aula INT NOT NULL,
    id_pergunta INT NOT NULL,
    PRIMARY KEY (id_aula, id_pergunta),
    FOREIGN KEY (id_aula) REFERENCES aula(id_aula),
    FOREIGN KEY (id_pergunta) REFERENCES perguntas(id_pergunta)
);

CREATE TABLE temas (
    id_tema SERIAL PRIMARY KEY,
    tema TEXT NOT NULL
);

CREATE TABLE pergunta_tema (
    id_pergunta INT NOT NULL,
    id_tema INT NOT NULL,
    PRIMARY KEY (id_pergunta, id_tema),
    FOREIGN KEY (id_pergunta) REFERENCES perguntas(id_pergunta),
    FOREIGN KEY (id_tema) REFERENCES temas(id_tema)
);

CREATE TABLE refresh_tokens (
  id SERIAL PRIMARY KEY,
  usuario_id INT NOT NULL,
  token_hash TEXT NOT NULL,
  revoked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);